### PR TITLE
Make User:logLogin public

### PR DESCRIPTION
**Pull request by module0x90**
I am planning to add an IP column, but to do that I need the logLogin function public, so that child classes can implement it as well.

### CODE REVIEW

**Comment by ptejada** [comment]
Hey, I don't see how making this function public will help you on your task. I guessing this is what you are doing but an I don't see issue with it:
```
class MyUser extends \ptejada\uFlex\User {
    protected function logLogin()
    {
        // Do your thing here here
    }
}
```

**Comment by module0x90** [comment]
Pablo,

On Wed, Feb 03, 2016 at 05:03:20PM -0800, Pablo Tejada wrote:
>    Hey, I don't see how making this function public will help you on your
>    task. I guessing this is what you are doing but an I don't see issue
>    with it:
> class MyUser extends \ptejada\uFlex\User {
>     protected function logLogin()
>     {
>         // Do your thing here here
>     }
> }

Then we would loose the existing functionality, ie. that it is updating
the LastLogin column.

In my subclass I would do a

parent::logLogin();

first to retain your existing functionality and then update the IP column
(what I am still gonna add).

Ah sorry, I am with you now, I am implementing this as a sub class, and
not directly in your class User. Please ignore this PR.


Regards

Thomas


-- 
www.preissler.co.uk | Twitter: @module0x90

**Comment by ptejada** [comment]
Hey Thomas,
Additionally, consider just copying the code of the existing functionality into your sub-class and add IP your IP column. It will save one SQL query. Example: 

```php
class MyUser extends \ptejada\uFlex\User {
    protected function logLogin()
    {
        //Update last_login
        $time = time();
        $sql = "UPDATE _table_ SET LastLogin=:stamp, IP=:ip WHERE ID=:id";
        if ($this->table->runQuery($sql, array('stamp' => $time, 'id' => $this->ID, 'ip' => $userIP))) {
            $this->log->report('Last Login updated');
        }
        
        // Note: no need to call the parent method
    }
}
```
Doing a separate query to update the IP should be fine too, just something to consider.

**Comment by module0x90** [comment]
Pablo,

thank you very much, but I am not keen on copying code around. It 
duplicates things and makes it difficult to maintain. And it violates the 
DRY (Don't Repeat Yourself) principle. We have classes, so let's use them 
to their fullest.

I won't use a separate class and will implement it directly in yours.

You might still want to reconsider and change that function to public, 
somebody else might want to be able to make a subclass and extend that 
function.


BR

Thomas

-- 
www​.​preissler​.​co​.​uk | Twitter: @module0x90

**Comment by ptejada** [comment]
Thomas,

Im not sure if you are confusing protected with private, but a protected method can be overwritten/extended by a sub class.

**Comment by module0x90** [comment]
On Wed, Feb 03, 2016 at 06:50:07PM -0800, Pablo Tejada wrote:
>    Thomas,
> 
>    Im not sure if you are confusing protected with private, but a
>    protected method can be overwritten/extended by a sub class.

Yeah, you are absolutely right. Spot on.
I absolutely misunderstood it for some reason.

I guess it must have been too late here... :-)


Cheers


> 
>    --
>    Reply to this email directly or [1]view it on GitHub.
> 
> References
> 
>    1. https://github.com/ptejada/uFlex/pull/35#issuecomment-179590012

-- 
www.preissler.co.uk | Twitter: @module0x90

**Pull request closed without merging**
